<?php
declare(strict_types=1);

// NasaOpenApis SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

NasaOpenApisUtility::setRegistrar(function (NasaOpenApisUtility $u): void {
    $u->clean = [NasaOpenApisClean::class, 'call'];
    $u->done = [NasaOpenApisDone::class, 'call'];
    $u->make_error = [NasaOpenApisMakeError::class, 'call'];
    $u->feature_add = [NasaOpenApisFeatureAdd::class, 'call'];
    $u->feature_hook = [NasaOpenApisFeatureHook::class, 'call'];
    $u->feature_init = [NasaOpenApisFeatureInit::class, 'call'];
    $u->fetcher = [NasaOpenApisFetcher::class, 'call'];
    $u->make_fetch_def = [NasaOpenApisMakeFetchDef::class, 'call'];
    $u->make_context = [NasaOpenApisMakeContext::class, 'call'];
    $u->make_options = [NasaOpenApisMakeOptions::class, 'call'];
    $u->make_request = [NasaOpenApisMakeRequest::class, 'call'];
    $u->make_response = [NasaOpenApisMakeResponse::class, 'call'];
    $u->make_result = [NasaOpenApisMakeResult::class, 'call'];
    $u->make_point = [NasaOpenApisMakePoint::class, 'call'];
    $u->make_spec = [NasaOpenApisMakeSpec::class, 'call'];
    $u->make_url = [NasaOpenApisMakeUrl::class, 'call'];
    $u->param = [NasaOpenApisParam::class, 'call'];
    $u->prepare_auth = [NasaOpenApisPrepareAuth::class, 'call'];
    $u->prepare_body = [NasaOpenApisPrepareBody::class, 'call'];
    $u->prepare_headers = [NasaOpenApisPrepareHeaders::class, 'call'];
    $u->prepare_method = [NasaOpenApisPrepareMethod::class, 'call'];
    $u->prepare_params = [NasaOpenApisPrepareParams::class, 'call'];
    $u->prepare_path = [NasaOpenApisPreparePath::class, 'call'];
    $u->prepare_query = [NasaOpenApisPrepareQuery::class, 'call'];
    $u->graphql_body = [NasaOpenApisGraphql::class, 'body'];
    $u->graphql_errors = [NasaOpenApisGraphql::class, 'errors'];
    $u->result_basic = [NasaOpenApisResultBasic::class, 'call'];
    $u->result_body = [NasaOpenApisResultBody::class, 'call'];
    $u->result_headers = [NasaOpenApisResultHeaders::class, 'call'];
    $u->transform_request = [NasaOpenApisTransformRequest::class, 'call'];
    $u->transform_response = [NasaOpenApisTransformResponse::class, 'call'];
});
